### ISSUE TITLE
[R6] IllegalStateException when running /re glass

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#129]
The following error is displayed after running /re glass:
```
17.01 18:02:30 [Server] WARN java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
17.01 18:02:30 [Server] WARN at net.minecraft.server.v1_10_R1.MCUtil.ensureMain(MCUtil.java:40)
17.01 18:02:30 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
17.01 18:02:30 [Server] WARN at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:163)
17.01 18:02:30 [Server] WARN at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:146)
17.01 18:02:30 [Server] WARN at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:142)
17.01 18:02:30 [Server] WARN at net.minecraft.server.v1_10_R1.World.getType(World.java:831)
17.01 18:02:30 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayOutBlockChange.<init>(SourceFile:23)
17.01 18:02:30 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:451)
17.01 18:02:30 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:444)
17.01 18:02:30 [Server] WARN at react.controller.GlassController$1.run(GlassController.java:104)
17.01 18:02:30 [Server] WARN at react.gconcurrent.A$1.run(A.java:14)
17.01 18:02:30 [Server] WARN at react.gconcurrent.ParallelThread.execute(ParallelThread.java:63)
17.01 18:02:30 [Server] WARN at react.gconcurrent.ParallelThread.execute(ParallelThread.java:81)
17.01 18:02:30 [Server] WARN at react.gconcurrent.ParallelThread.run(ParallelThread.java:32)
17.01 18:02:30 [Server] WARN java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
17.01 18:02:30 [Server] WARN at net.minecraft.server.v1_10_R1.MCUtil.ensureMain(MCUtil.java:40)
17.01 18:02:30 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
17.01 18:02:30 [Server] WARN at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:163)
17.01 18:02:30 [Server] WARN at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:146)
17.01 18:02:30 [Server] WARN at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:142)
17.01 18:02:30 [Server] WARN at net.minecraft.server.v1_10_R1.World.getType(World.java:831)
17.01 18:02:30 [Server] WARN at net.minecraft.server.v1_10_R1.PacketPlayOutBlockChange.<init>(SourceFile:23)
17.01 18:02:30 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:451)
17.01 18:02:30 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.entity.CraftPlayer.sendBlockChange(CraftPlayer.java:444)
17.01 18:02:30 [Server] WARN at react.controller.GlassController$1.run(GlassController.java:104)
17.01 18:02:30 [Server] WARN at react.gconcurrent.A$1.run(A.java:14)
17.01 18:02:30 [Server] WARN at react.gconcurrent.ParallelThread.execute(ParallelThread.java:63)
17.01 18:02:30 [Server] WARN at react.gconcurrent.ParallelThread.execute(ParallelThread.java:81)
17.01 18:02:30 [Server] WARN at react.gconcurrent.ParallelThread.run(ParallelThread.java:32)
```

TacoSpigot 1.10.2-R0.1-SNAPSHOT
React-6.24129a

**Comment by cyberpwnn** [comment]
Fixed in 6.27159a
