### ISSUE TITLE
CurrentModificationException on stop

### ISSUE THREAD

**Issue by GwnDaan** [VolmitSoftware/React#134]
Server Version:  git-Paper-1298 (MC: 1.12.2)
React Version: v6.26120a

Stacktrace:
```
[21:25:57] [Server thread/ERROR]: Error occurred while disabling React v6.26120a (Is it up to date?)
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(Unknown Source) ~[?:1.8.0_151]
	at java.util.HashMap$KeyIterator.next(Unknown Source) ~[?:1.8.0_151]
	at react.controller.PlayerController.stop(PlayerController.java:33) ~[?:?]
	at react.surge.Main.shutDownAmps(Main.java:270) ~[?:?]
	at react.surge.Main.onStop(Main.java:210) ~[?:?]
	at react.surge.control.AmpedPlugin.onDisable(AmpedPlugin.java:90) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot.jar:git-Paper-1298]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:344) [spigot.jar:git-Paper-1298]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:425) [spigot.jar:git-Paper-1298]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:418) [spigot.jar:git-Paper-1298]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:351) [spigot.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:486) [spigot.jar:git-Paper-1298]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:701) [spigot.jar:git-Paper-1298]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

**Comment by cyberpwnn** [comment]
Fixed in 6.27159a
