### ISSUE TITLE
[R6] NoSuchMethodError on stop

### ISSUE THREAD

**Issue by GwnDaan** [VolmitSoftware/React#137]
Server Version:  git-Spigot-9b8bba4-bdcc7c7 (MC: 1.12.2)
React Version: React v6.26411a

Stacktrace:
```
[15:05:05 ERROR]: Error occurred while disabling React v6.26411a (Is it up to date?)
java.lang.NoSuchMethodError: null
        at java.lang.Thread.destroy(Unknown Source) ~[?:1.8.0_151]
        at react.surge.Main.onStop(Main.java:242) ~[?:?]
        at react.surge.control.AmpedPlugin.onDisable(AmpedPlugin.java:90) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:361) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:422) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:415) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.disablePlugins(CraftServer.java:349) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:465) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:613) [spigot.jar:git-Spigot-9b8bba4-bdcc7c7]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

**Comment by cyberpwnn** [comment]
#141

Fixed in 6.27159a
