### ISSUE TITLE
[R6] WorldMonitor: Asynchronous Async Chunk Load

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#138]
```
19.01 13:30:39 [Server] INFO React: [RAI]: It seems like the server is failing to keep a stable chunk tick
19.01 13:30:39 [Server] INFO React: [RAI]: Looks like we are now keeping a stable chunk tick
19.01 13:30:40 [Server] WARN java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
19.01 13:30:40 [Server] WARN at net.minecraft.server.v1_10_R1.MCUtil.ensureMain(MCUtil.java:40)
19.01 13:30:40 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
19.01 13:30:40 [Server] WARN at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:163)
19.01 13:30:40 [Server] WARN at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:146)
19.01 13:30:40 [Server] WARN at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:142)
19.01 13:30:40 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:149)
19.01 13:30:40 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getBlockAt(CraftWorld.java:93)
19.01 13:30:40 [Server] WARN at org.bukkit.craftbukkit.v1_10_R1.CraftChunk.getTileEntities(CraftChunk.java:110)
19.01 13:30:40 [Server] WARN at react.surge.server.WorldMonitor.sampleTileCount(WorldMonitor.java:227)
19.01 13:30:40 [Server] WARN at react.surge.server.WorldMonitor.sample(WorldMonitor.java:161)
19.01 13:30:40 [Server] WARN at react.surge.server.WorldMonitor.run(WorldMonitor.java:52)
```

PaperSpigot 1.10.2
React-6.26411a

**Comment by cyberpwnn** [comment]
Fixed in 6.27159a
