### ISSUE TITLE
[R6] NoSuchMethodError when running /re a ce

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#139]
```
19.01 13:40:20 [Server] WARN Task #19 for React v6.26411a generated an exception
19.01 13:40:20 [Server] INFO java.lang.NoSuchMethodError: org.bukkit.entity.Entity.getPassengers()Ljava/util/List;
19.01 13:40:20 [Server] INFO at react.api.EntityFlag.is(EntityFlag.java:62) ~[?:?]
19.01 13:40:20 [Server] INFO at react.api.EntityFlag.getFlags(EntityFlag.java:29) ~[?:?]
19.01 13:40:20 [Server] INFO at react.controller.EntityCullController.partialCull(EntityCullController.java:209) ~[?:?]
19.01 13:40:20 [Server] INFO at react.controller.EntityCullController.cull(EntityCullController.java:175) ~[?:?]
19.01 13:40:20 [Server] INFO at react.action.ActionCullEntities.cull(ActionCullEntities.java:154) ~[?:?]
19.01 13:40:20 [Server] INFO at react.action.ActionCullEntities.enact(ActionCullEntities.java:104) ~[?:?]
19.01 13:40:20 [Server] INFO at react.api.Action.act(Action.java:183) ~[?:?]
19.01 13:40:20 [Server] INFO at react.controller.ActionController.fireAction(ActionController.java:122) ~[?:?]
19.01 13:40:20 [Server] INFO at react.controller.ActionController.tick(ActionController.java:171) ~[?:?]
19.01 13:40:20 [Server] INFO at react.surge.Main.onTick(Main.java:641) ~[?:?]
19.01 13:40:20 [Server] INFO at react.surge.PluginAmp.masterTick(PluginAmp.java:79) ~[?:?]
19.01 13:40:20 [Server] INFO at react.surge.PluginAmp.access$0(PluginAmp.java:67) ~[?:?]
19.01 13:40:20 [Server] INFO at react.surge.PluginAmp$3.run(PluginAmp.java:62) ~[?:?]
19.01 13:40:20 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.10.2.jar:git-Paper-916.2]
19.01 13:40:20 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.10.2.jar:git-Paper-916.2]
19.01 13:40:20 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:798) [patched_1.10.2.jar:git-Paper-916.2]
19.01 13:40:20 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916.2]
19.01 13:40:20 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916.2]
19.01 13:40:20 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916.2]
19.01 13:40:20 [Server] INFO at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
```

PaperSpigot 1.10.2
React-6.26411a

**Comment by cyberpwnn** [comment]
Fixed in 6.27159a
