### ISSUE TITLE
Error upon joining

### ISSUE THREAD

**Issue by CaptainAmpersand** [VolmitSoftware/React#153]
```
[03:06:40] [Server thread/WARN]: java.lang.IllegalArgumentException: Can not set boolean field react.api.ReactPlayer.highMonitor to java.util.ArrayList
[03:06:40] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:167)
[03:06:40] [Server thread/WARN]: 	at sun.reflect.UnsafeFieldAccessorImpl.throwSetIllegalArgumentException(UnsafeFieldAccessorImpl.java:171)
[03:06:40] [Server thread/WARN]: 	at sun.reflect.UnsafeBooleanFieldAccessorImpl.set(UnsafeBooleanFieldAccessorImpl.java:86)
[03:06:40] [Server thread/WARN]: 	at java.lang.reflect.Field.set(Field.java:764)
[03:06:40] [Server thread/WARN]: 	at react.surge.cluster.ConfigurationDataInput.read(ConfigurationDataInput.java:122)
[03:06:40] [Server thread/WARN]: 	at react.api.ReactPlayer.load(ReactPlayer.java:122)
[03:06:40] [Server thread/WARN]: 	at react.api.ReactPlayer.<init>(ReactPlayer.java:97)
[03:06:40] [Server thread/WARN]: 	at react.controller.PlayerController.getPlayer(PlayerController.java:105)
[03:06:40] [Server thread/WARN]: 	at react.controller.MonitorController.on(MonitorController.java:513)
[03:06:40] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[03:06:40] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[03:06:40] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[03:06:40] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:498)
[03:06:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302)
[03:06:40] [Server thread/WARN]: 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
[03:06:40] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
[03:06:40] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
[03:06:40] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.onPlayerJoin(PlayerList.java:346)
[03:06:40] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:166)
[03:06:40] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:159)
[03:06:40] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:57)
[03:06:40] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:233)
[03:06:40] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:140)
[03:06:40] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:845)
[03:06:40] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
[03:06:40] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
[03:06:40] [Server thread/WARN]: 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
[03:06:40] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

6.0.33a version. Server crashed 3 times so far 5 seconds upon startup. Not sure if that's related to this or not, but working on it.
Spigot 1.12.2

**Comment by cyberpwnn** [comment]
Update
