### ISSUE TITLE
NumberFormatException error

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#165]
Running /re help <not a number> throws a NumberFormatException:

![Error in-game](https://i.imgur.com/TaDOKPr.png)

```
13.02 16:50:21 [Server] ERROR null
13.02 16:50:21 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 're' in plugin React v6.0.51
13.02 16:50:21 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:672) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1398) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1203) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
13.02 16:50:21 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
13.02 16:50:21 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
13.02 16:50:21 [Server] INFO Caused by: java.lang.NumberFormatException: For input string: "a"
13.02 16:50:21 [Server] INFO at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[?:1.8.0_161]
13.02 16:50:21 [Server] INFO at java.lang.Integer.parseInt(Integer.java:580) ~[?:1.8.0_161]
13.02 16:50:21 [Server] INFO at java.lang.Integer.valueOf(Integer.java:766) ~[?:1.8.0_161]
13.02 16:50:21 [Server] INFO at react.command.CommandHelp.fire(CommandHelp.java:44) ~[React-6.0.51-origin.jar:?]
13.02 16:50:21 [Server] INFO at react.controller.CommandController.onCommand(CommandController.java:292) ~[React-6.0.51-origin.jar:?]
13.02 16:50:21 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
13.02 16:50:21 [Server] INFO ... 15 more
```

---
React v6.0.51
Tested with PaperSpigot and TacoSpigot 1.10.

**Comment by cyberpwnn** [comment]
Fixed
