### ISSUE TITLE
NoClassDefFoundError when running /re map (-i)

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#167]
```
15.02 09:59:04 [Server] ERROR null
15.02 09:59:04 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 're' in plugin React v6.0.53
15.02 09:59:04 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:672) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1398) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1203) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:5) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
15.02 09:59:04 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
15.02 09:59:04 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:808) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
15.02 09:59:04 [Server] INFO Caused by: java.lang.NoClassDefFoundError: react/graph/GraphSize$1
15.02 09:59:04 [Server] INFO at react.graph.GraphSize.toPoint(GraphSize.java:11) ~[React-6.0.53-origin.jar:?]
15.02 09:59:04 [Server] INFO at react.graph.ColossalView$Builder.compute(ColossalView.java:186) ~[React-6.0.53-origin.jar:?]
15.02 09:59:04 [Server] INFO at react.graph.GraphingInstance.compile(GraphingInstance.java:405) ~[React-6.0.53-origin.jar:?]
15.02 09:59:04 [Server] INFO at react.controller.GraphController.toggleMapping(GraphController.java:258) ~[React-6.0.53-origin.jar:?]
15.02 09:59:04 [Server] INFO at react.command.CommandMap.fire(CommandMap.java:40) ~[React-6.0.53-origin.jar:?]
15.02 09:59:04 [Server] INFO at react.controller.CommandController.onCommand(CommandController.java:292) ~[React-6.0.53-origin.jar:?]
15.02 09:59:04 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO ... 15 more
15.02 09:59:04 [Server] INFO Caused by: java.lang.ClassNotFoundException: react.graph.GraphSize$1
15.02 09:59:04 [Server] INFO at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_161]
15.02 09:59:04 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_161]
15.02 09:59:04 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_161]
15.02 09:59:04 [Server] INFO at react.graph.GraphSize.toPoint(GraphSize.java:11) ~[React-6.0.53-origin.jar:?]
15.02 09:59:04 [Server] INFO at react.graph.ColossalView$Builder.compute(ColossalView.java:186) ~[React-6.0.53-origin.jar:?]
15.02 09:59:04 [Server] INFO at react.graph.GraphingInstance.compile(GraphingInstance.java:405) ~[React-6.0.53-origin.jar:?]
15.02 09:59:04 [Server] INFO at react.controller.GraphController.toggleMapping(GraphController.java:258) ~[React-6.0.53-origin.jar:?]
15.02 09:59:04 [Server] INFO at react.command.CommandMap.fire(CommandMap.java:40) ~[React-6.0.53-origin.jar:?]
15.02 09:59:04 [Server] INFO at react.controller.CommandController.onCommand(CommandController.java:292) ~[React-6.0.53-origin.jar:?]
15.02 09:59:04 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[TacoSpigot%201.10.jar:git-TacoSpigot-7af2abbe]
15.02 09:59:04 [Server] INFO ... 15 more
15.02 09:59:04 [Server] INFO React: Failed to tick GraphController
15.02 09:59:04 [Server] INFO React: Failed to tick GraphController
15.02 09:59:04 [Server] INFO React: Failed to tick GraphController
15.02 09:59:04 [Server] INFO React: Failed to tick GraphController
15.02 09:59:04 [Server] INFO React: Failed to tick GraphController
15.02 09:59:04 [Server] INFO React: Failed to tick GraphController
15.02 09:59:04 [Server] INFO React: Failed to tick GraphController
15.02 09:59:04 [Server] INFO React: Failed to tick GraphController
15.02 09:59:04 [Server] INFO React: Failed to tick GraphController
15.02 09:59:04 [Server] INFO React: Failed to tick GraphController
15.02 09:59:04 [Server] INFO React: Failed to tick GraphController
15.02 09:59:05 [Server] INFO React: Failed to tick GraphController
15.02 09:59:05 [Server] INFO React: Failed to tick GraphController
15.02 09:59:05 [Server] INFO React: Failed to tick GraphController
15.02 09:59:05 [Server] INFO React: Failed to tick GraphController
15.02 09:59:05 [Server] INFO React: Failed to tick GraphController
15.02 09:59:05 [Server] INFO React: Failed to tick GraphController
15.02 09:59:05 [Server] INFO React: Failed to tick GraphController
15.02 09:59:05 [Server] INFO React: Failed to tick GraphController
15.02 09:59:06 [Server] INFO React: Failed to tick GraphController
15.02 09:59:06 [Server] INFO React: Failed to tick GraphController
15.02 09:59:06 [Server] INFO React: Failed to tick GraphController
15.02 09:59:06 [Server] INFO React: Failed to tick GraphController
15.02 09:59:06 [Server] INFO React: Failed to tick GraphController
15.02 09:59:06 [Server] INFO React: Failed to tick GraphController
15.02 09:59:06 [Server] INFO React: Failed to tick GraphController
15.02 09:59:06 [Server] INFO React: Failed to tick GraphController
15.02 09:59:06 [Server] INFO React: Failed to tick GraphController
15.02 09:59:06 [Server] INFO React: Failed to tick GraphController
15.02 09:59:06 [Server] INFO React: Failed to tick GraphController
15.02 09:59:06 [Server] INFO React: Failed to tick GraphController
```

---
React v6.0.53
Tested with PaperSpigot and TacoSpigot 1.10.

**Comment by cyberpwnn** [comment]
Fixed
