### ISSUE TITLE
React V6.0.1 dont working with Thermos.

### ISSUE THREAD

**Issue by SantyPlays** [VolmitSoftware/React#187]
```
[06:12:42] [Server thread/INFO]: [React] Enabling React v6.0.1
[06:12:44] [Server thread/ERROR]: Error occurred while enabling React v6.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bukkit/event/entity/EntitySpawnEvent
    at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_151]
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_151]
    at java.lang.Class.getDeclaredMethod(Class.java:2128) ~[?:1.8.0_151]
    at java.lang.Thread$1.run(Thread.java:1674) ~[?:1.8.0_151]
    at java.lang.Thread$1.run(Thread.java:1667) ~[?:1.8.0_151]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_151]
    at java.lang.Thread.auditSubclass(Thread.java:1666) ~[?:1.8.0_151]
    at java.lang.Thread.isCCLOverridden(Thread.java:1653) ~[?:1.8.0_151]
    at java.lang.Thread.init(Thread.java:400) ~[?:1.8.0_151]
    at java.lang.Thread.init(Thread.java:349) ~[?:1.8.0_151]
    at java.lang.Thread.<init>(Thread.java:448) ~[?:1.8.0_151]
    at surge.server.WorldMonitor.<init>(WorldMonitor.java:40) ~[?:?]
    at surge.server.SuperSampler$1.<init>(SuperSampler.java:72) ~[?:?]
at surge.server.SuperSampler.<init>(SuperSampler.java:71) ~[?:?]
    at surge.Main.onStart(Main.java:134) ~[?:?]
    at surge.control.AmpedPlugin.onEnable(AmpedPlugin.java:86) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:1.7.10-1614.57]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:1.7.10-1614.57]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:1.7.10-1614.57]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:438) [CraftServer.class:1.7.10-1614.57]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:372) [CraftServer.class:1.7.10-1614.57]
    at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:463) [ayq.class:?]
    at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
    at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
    at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
    at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
    at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class
```

**Comment by Frerduro** [comment]
Thermos is not supported...

**Comment by cyberpwnn** [comment]
Correct it is not. I will add support

**Comment by Frerduro** [comment]
Soon™

**Comment by cyberpwnn** [comment]
Mind if you pm me the jar you are using on discord? Thermos

**Comment by SantyPlays** [comment]
Fine

**Comment by SantyPlays** [comment]
Okey, i sended you the jar 
my Discord is Santiago#4509

**Comment by cyberpwnn** [comment]
Thanks

**Comment by SantyPlays** [comment]
Is fixed?
