### ISSUE TITLE
React v6.0.2 is induce tps drop

### ISSUE THREAD

**Issue by B4TT3RY** [VolmitSoftware/React#194]
Timings: https://timings.aikar.co/?id=2fc703ce491246af8016fec0ec78ceae

And React v6 is not loaded into plugman.

**Comment by cyberpwnn** [comment]
It looks like its react in the scheduler. Im adding some profiling to help find out what is causing it. Timings isnt showing it.

**Comment by B4TT3RY** [comment]
/plugman load React

[18:22:37 WARN]: java.util.zip.ZipException: only DEFLATED entries can have EXT descriptor
[18:22:37 WARN]:        at java.util.zip.ZipInputStream.readLOC(Unknown Source)              
[18:22:37 WARN]:        at java.util.zip.ZipInputStream.getNextEntry(Unknown Source)         
[18:23:37 WARN]:        at surge.server.CPS.scan(CPS.java:61)                                
[18:22:37 WARN]:        at react.controller.SpikeController$1$1.run(SpikeController.java:48) 
[18:22:37 WARN]:        at react.gconcurrent.A$1.run(A.java:14)                              
[18:22:37 WARN]:        at react.gconcurrent.ParallelThread.execute(ParallelThread.java:68)  
[18:22:37 WARN]:        at react.gconcurrent.ParallelThread.execute(ParallelThread.java:86)  
[18:22:37 WARN]:        at react.gconcurrent.ParallelThread.run(ParallelThread.java:32)      

[18:23:06 INFO]: React: Super Sampler did not start correctly. Resetting

What's this error? and TPS is 13
