### ISSUE TITLE
Failed to tick FastDecayController || InstantDropController class not found. using 1.8.8 latest spigot 

### ISSUE THREAD

**Issue by LuckyClutch07** [VolmitSoftware/React#219]
This is quite annoying on the console it spams how can I fix this?
the server has ViaVersion and ViaRewind to allow 1.7 - 1.12 connections

**Comment by LuckyClutch07** [comment]
I am also getting this error spammed as well for arrow or some sort
` [React] Task #25 for React v6.0.3 generated an exception
java.lang.NoSuchMethodError: org.bukkit.entity.Arrow.getPickupStatus()Lorg/bukkit/entity/Arrow$PickupStatus;
        at react.controller.InstantDropController$1.run(InstantDropController.java:127) ~[?:?]
        at react.gconcurrent.S$1.run(S.java:14) ~[?:?]
        at react.gconcurrent.ParallelPoolManager.tickSyncQueue(ParallelPoolManager.java:35) ~[?:?]
        at surge.Main.onTick(Main.java:576) ~[?:?]
        at surge.PluginAmp.masterTick(PluginAmp.java:78) ~[?:?]
        at surge.PluginAmp.access$000(PluginAmp.java:10) ~[?:?]
        at surge.PluginAmp$3.run(PluginAmp.java:61) ~[?:?]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [spigot.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [spigot.jar:git-Spigot-db6de12-18fbb24]
`

**Comment by lucas2107** [comment]
Try using React 6.0.6

**Comment by cyberpwnn** [comment]
So it doesnt matter what ViaRewind supports. What version is the server.

**Comment by lucas2107** [comment]
Having something in verbose sometimes: http://prntscr.com/incdip

Paper 1.8.8 / R6.0.6

**Comment by cyberpwnn** [comment]
Fixed in 6.1.1
