### ISSUE TITLE
NoSuchElementException: GoalReducedEntityCounts

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#226]
```
[Server thread/WARN]: [React] Task #99049 for React v6.0.9 generated an exception
java.util.NoSuchElementException
	at org.bukkit.craftbukkit.v1_10_R1.util.UnsafeList$Itr.next(UnsafeList.java:248) ~[patched_1.10.2.jar:git-Paper-916.2]
	at java.util.AbstractCollection.toArray(AbstractCollection.java:141) ~[?:1.8.0_161]
	at org.bukkit.craftbukkit.v1_10_R1.CraftChunk.getEntities(CraftChunk.java:86) ~[patched_1.10.2.jar:git-Paper-916.2]
	at react.rai.goals.GoalReducedEntityCounts.onPropigated(GoalReducedEntityCounts.java:121) ~[React-6.0.9.jar:?]
	at react.rai.Goal.propigate(Goal.java:43) ~[React-6.0.9.jar:?]
	at react.rai.Goal$1.run(Goal.java:38) ~[React-6.0.9.jar:?]
	at react.gconcurrent.S$1.run(S.java:14) ~[React-6.0.9.jar:?]
	at react.gconcurrent.ParallelPoolManager.tickSyncQueue(ParallelPoolManager.java:39) ~[React-6.0.9.jar:?]
	at surge.Main.onTick(Main.java:588) ~[React-6.0.9.jar:?]
	at surge.PluginAmp.masterTick(PluginAmp.java:85) ~[React-6.0.9.jar:?]
	at surge.PluginAmp.access$000(PluginAmp.java:11) ~[React-6.0.9.jar:?]
	at surge.PluginAmp$3.run(PluginAmp.java:65) ~[React-6.0.9.jar:?]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:58) ~[patched_1.10.2.jar:git-Paper-916.2]
	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:355) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:798) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:404) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:740) [patched_1.10.2.jar:git-Paper-916.2]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:639) [patched_1.10.2.jar:git-Paper-916.2]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
```

React v6.0.9
PaperSpigot 1.10.2

**Comment by cyberpwnn** [comment]
Fixed in 6.1.1
