### ISSUE TITLE
java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 

### ISSUE THREAD

**Issue by B4TT3RY** [VolmitSoftware/React#288]
```
[21:24:15] [React Reactor/WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns 
[21:24:15] [React Reactor/WARN]: 	at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:54)
[21:24:15] [React Reactor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[21:24:15] [React Reactor/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164)
[21:24:15] [React Reactor/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147)
[21:24:15] [React Reactor/WARN]: 	at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143)
[21:24:15] [React Reactor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getChunkAt(CraftWorld.java:181)
[21:24:15] [React Reactor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.CraftWorld.getBlockAt(CraftWorld.java:118)
[21:24:15] [React Reactor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:193)
[21:24:15] [React Reactor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:201)
[21:24:15] [React Reactor/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.getRelative(CraftBlock.java:197)
[21:24:15] [React Reactor/WARN]: 	at com.volmit.react.util.W.blockFaces(W.java:609)
[21:24:15] [React Reactor/WARN]: 	at com.volmit.react.util.BlockFinder.tail(BlockFinder.java:30)
[21:24:15] [React Reactor/WARN]: 	at com.volmit.react.util.BlockFinder.tail(BlockFinder.java:34)
[21:24:15] [React Reactor/WARN]: 	at com.volmit.react.util.BlockFinder.tail(BlockFinder.java:34)
[21:24:15] [React Reactor/WARN]: 	at com.volmit.react.util.BlockFinder.tail(BlockFinder.java:34)
[21:24:15] [React Reactor/WARN]: 	at com.volmit.react.util.BlockFinder.tail(BlockFinder.java:34)
[21:24:15] [React Reactor/WARN]: 	at com.volmit.react.util.BlockFinder.follow(BlockFinder.java:20)
[21:24:15] [React Reactor/WARN]: 	at com.volmit.react.controller.FastDecayController$3$1.run(FastDecayController.java:133)
[21:24:15] [React Reactor/WARN]: 	at com.volmit.react.util.RQ.run(RQ.java:25)
```

```
[21:24:47] [Server thread/INFO]: React version 6.3.2
[21:24:47] [Server thread/INFO]: React is a smart performance plugin designed to automatically fix lag from the source.
[21:24:47] [Server thread/INFO]: Website: https://www.spigotmc.org/resources/react-smart-server-performance.21057/
[21:24:47] [Server thread/INFO]: Author: cyberpwn
```

```
[21:24:55] [Server thread/INFO]: This server is running Paper version git-Paper-1373 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
```

```
Search "java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns " (92 hits in 1 file)
  C:\Users\Administrator\Desktop\latest.log (92 hits)
```

**Comment by cyberpwnn** [comment]
Fixed in 6.3.3
