### ISSUE TITLE
Concurrent Modification

### ISSUE THREAD

**Issue by cyberpwnn** [VolmitSoftware/React#365]
```
[18:14:47] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
    at java.util.HashMap$HashIterator.nextNode(HashMap.java:1429) ~[?:1.8.0_72]
    at java.util.HashMap$KeyIterator.next(HashMap.java:1453) ~[?:1.8.0_72]
    at net.minecraft.server.v1_12_R1.EntityTracker.updatePlayers(EntityTracker.java:180) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
    at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:834) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
    at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
    at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) ~[spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
    at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-4bd94dc-f4ca180]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
```

**Comment by cyberpwnn** [comment]
```yml
tick-smearing:
    tiles:

      # Allow the tile tick throttle to be X higher than the current time to prevent
      # odd skipping of entities, and to allow room for error.
      seperation-bias: 0.07

      # How many ticks should the tick time be averaged across to compute biases
      smear-factor: 50.0

      # The maximum tile tick time before throttling
      max-time: 35.0

      # Enable entity tick throttling
      enable: false
    entities:

      # How many ticks should the tick time be averaged across to compute biases
      smear-factor: 50.0

      # Enable entity tick throttling
      enable: false

      # The maximum tile tick time before throttling
      max-time: 25.0

      # Allow the tile tick throttle to be X higher than the current time to prevent
      # odd skipping of entities, and to allow room for error.
      seperation-bias: 10.0
```

Turn off smear ticking
