### ISSUE TITLE
React fails to interact with classmexer

### ISSUE THREAD

**Issue by cyberpwnn** [VolmitSoftware/React#366]
https://gyazo.com/0ed645d4f7e976c9920bb3f4e969efa5

**Comment by LogGits** [comment]
Error caused by /re mem react:
```
WARN 26/05/2018 05:23:54
05:23:54java.lang.reflect.InvocationTargetException
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.volmit.react.controller.MemoryController.getMemoryUsage(MemoryController.java:28)
at com.volmit.react.command.CommandMem$4.run(CommandMem.java:194)
at com.volmit.react.util.RQ.run(RQ.java:25)
Caused by: java.lang.NoClassDefFoundError: Lcom/drtshock/playervaults/PlayerVaults;
at java.lang.Class.getDeclaredFields0(Native Method)
at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
at java.lang.Class.getDeclaredFields(Class.java:1916)
at com.javamex.classmexer.MemoryUtil.deepMemoryUsageOf0(MemoryUtil.java:197)
at com.javamex.classmexer.MemoryUtil.deepMemoryUsageOf(MemoryUtil.java:104)
at com.javamex.classmexer.MemoryUtil.deepMemoryUsageOf(MemoryUtil.java:80)
... 7 more
Caused by: java.lang.ClassNotFoundException: com.drtshock.playervaults.PlayerVaults
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156)
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 13 more
```

**Comment by cyberpwnn** [comment]
My theory is some plugin is getting classloaded in some wrong way (maybe a class load issue if pv isnt installed)

**Comment by cyberpwnn** [comment]
Fixed by not sampling the plugin manager. Made it more accurate too!

**Comment by lucas2107** [comment]
React is locking at 55% of check for me and some plugins are saying 0.00 Bytes used.

**Comment by cyberpwnn** [comment]
Stop using /re mem top

Use something like /re mem Essentials

It requires a huge amount of classloading (and some plugins dont support it)

There isnt much i can fix here.
