### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by LogGits** [VolmitSoftware/React#379]
```
ERROR 03/06/2018 15:53:27
15:53:27Could not pass event PlayerMoveEvent to React v6.554
Console 03/06/2018 15:53:27
15:53:27org.bukkit.event.EventException: null
at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.12.2.jar:git-Paper-1416]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1416]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1416]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:515) ~[patched_1.12.2.jar:git-Paper-1416]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:500) ~[patched_1.12.2.jar:git-Paper-1416]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:692) ~[patched_1.12.2.jar:git-Paper-1416]
at net.minecraft.server.v1_12_R1.PacketPlayInFlying.a(SourceFile:126) ~[patched_1.12.2.jar:git-Paper-1416]
at net.minecraft.server.v1_12_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) ~[patched_1.12.2.jar:git-Paper-1416]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14) ~[patched_1.12.2.jar:git-Paper-1416]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_161]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_161]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [patched_1.12.2.jar:git-Paper-1416]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:843) [patched_1.12.2.jar:git-Paper-1416]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [patched_1.12.2.jar:git-Paper-1416]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) [patched_1.12.2.jar:git-Paper-1416]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [patched_1.12.2.jar:git-Paper-1416]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_161]
Caused by: java.lang.ArrayIndexOutOfBoundsException
```
patched_1.12.2.jar:git-Paper-1416
React v6.554

**Comment by LogGits** [comment]
thats literally what its printing to console:
https://gyazo.com/274f41c612519685f8e03eb4022face5

**Comment by cyberpwnn** [comment]
I need to know the cause, (text after `Caused by: java.lang.ArrayIndexOutOfBoundsException`)

If it isnt showing up try adding the jargs to your launch script `-XX:-OmitStackTraceInFastThrow`

**Comment by LogGits** [comment]
Unfortunately there isnt any text after that `caused by` line. I added the jarg to my launch script so if it happens again Il let you know. I am not sure how to reproduce the issue, it just randomly happened one day.

**Comment by cyberpwnn** [comment]
Cannot reproduce
