### ISSUE TITLE
Sampler issues React-6.566

### ISSUE THREAD

**Issue by CypherPhyre** [VolmitSoftware/React#418]
Getting the following in the console

```
[12:51:04] [React Reactor/WARN]: java.io.FileNotFoundException: plugins/React/cache/samplerdata-1530139725594.slg (No such file or directory)
[12:51:04] [React Reactor/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[12:51:04] [React Reactor/WARN]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[12:51:04] [React Reactor/WARN]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[12:51:04] [React Reactor/WARN]: 	at com.volmit.react.api.Datalog.openReadStream(Datalog.java:39)
[12:51:04] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.getDuration(DataLogArray.java:126)
[12:51:04] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.condense(DataLogArray.java:77)
[12:51:04] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.continuallyCondense(DataLogArray.java:52)
[12:51:04] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.beginNextStream(DataLogArray.java:346)
[12:51:04] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.sample(DataLogArray.java:438)
[12:51:04] [React Reactor/WARN]: 	at com.volmit.react.controller.DataLogController.onTickAsync(DataLogController.java:96)
[12:51:04] [React Reactor/WARN]: 	at com.volmit.react.util.TPSMonitor$3.run(TPSMonitor.java:166)
[12:51:04] [React Reactor/WARN]: 	at com.volmit.react.util.RQ.run(RQ.java:27)
[12:55:46] [Server thread/INFO]: Skipping schedule SavePlayerInv due to player amount[m
[13:00:46] [Server thread/INFO]: Skipping schedule Announcer due to player amount[m
[13:05:46] [Server thread/INFO]: Skipping schedule SavePlayerInv due to player amount[m
[13:15:47] [Server thread/INFO]: Skipping schedule Announcer due to player amount[m
[13:15:47] [Server thread/INFO]: Skipping schedule SavePlayerInv due to player amount[m
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: java.io.FileNotFoundException: plugins/React/cache/samplerdata-1530141527198.slg (No such file or directory)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at java.io.FileInputStream.open0(Native Method)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at java.io.FileInputStream.open(FileInputStream.java:195)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at com.volmit.react.api.Datalog.openReadStream(Datalog.java:39)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at com.volmit.react.api.DataLogArray.getDuration(DataLogArray.java:126)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at com.volmit.react.api.DataLogArray.condense(DataLogArray.java:77)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at com.volmit.react.api.DataLogArray.continuallyCondense(DataLogArray.java:52)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at com.volmit.react.api.DataLogArray.beginNextStream(DataLogArray.java:346)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at com.volmit.react.api.DataLogArray.sample(DataLogArray.java:438)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at com.volmit.react.controller.DataLogController.onTickAsync(DataLogController.java:96)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at com.volmit.react.util.TPSMonitor$3.run(TPSMonitor.java:166)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:25:35] [Craft Scheduler Thread - 1642/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[13:25:47] [Server thread/INFO]: Skipping schedule SavePlayerInv due to player amount[m
[13:28:36] [Server thread/INFO]: [0;36;1m[[0;32;22mReact[0;36;1m]: [0;32;1m[0;32;1m✔ [0;37;22mReact Reloaded[m
[13:28:37] [Server thread/INFO]: React: [0;37;1mLanguage: enUS[m
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: java.util.zip.ZipException: invalid stored block lengths
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at java.io.DataInputStream.readFully(DataInputStream.java:195)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at java.io.DataInputStream.readLong(DataInputStream.java:416)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at com.volmit.react.api.Datalog.openReadStream(Datalog.java:43)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at com.volmit.react.api.DataLogArray.getDuration(DataLogArray.java:126)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at com.volmit.react.api.DataLogArray.condense(DataLogArray.java:77)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at com.volmit.react.api.DataLogArray.continuallyCondense(DataLogArray.java:52)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at com.volmit.react.api.DataLogArray.beginNextStream(DataLogArray.java:346)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at com.volmit.react.api.DataLogArray.sample(DataLogArray.java:431)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at com.volmit.react.controller.DataLogController.onTickAsync(DataLogController.java:96)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at com.volmit.react.util.TPSMonitor$3.run(TPSMonitor.java:166)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[13:28:38] [Craft Scheduler Thread - 1655/WARN]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by cyberpwnn** [comment]
Fixed on 6.567
