### ISSUE TITLE
huh?

### ISSUE THREAD

**Issue by EthanTG** [VolmitSoftware/React#421]
```
|[09:25:14] [React Reactor/WARN]: java.io.EOFException: Unexpected end of ZLIB input stream
[09:25:14] [React Reactor/WARN]: 	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
[09:25:14] [React Reactor/WARN]: 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[09:25:14] [React Reactor/WARN]: 	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[09:25:14] [React Reactor/WARN]: 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
[09:25:14] [React Reactor/WARN]: 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
[09:25:14] [React Reactor/WARN]: 	at java.io.DataInputStream.readInt(DataInputStream.java:387)
[09:25:14] [React Reactor/WARN]: 	at java.io.DataInputStream.readFloat(DataInputStream.java:446)
[09:25:14] [React Reactor/WARN]: 	at com.volmit.react.api.Datalog.readStream(Datalog.java:67)
[09:25:14] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.merge(DataLogArray.java:106)
[09:25:14] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.condense(DataLogArray.java:81)
[09:25:14] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.continuallyCondense(DataLogArray.java:52)
[09:25:14] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.beginNextStream(DataLogArray.java:346)
[09:25:14] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.sample(DataLogArray.java:438)
[09:25:14] [React Reactor/WARN]: 	at com.volmit.react.controller.DataLogController.onTickAsync(DataLogController.java:96)
[09:25:14] [React Reactor/WARN]: 	at com.volmit.react.util.TPSMonitor$3.run(TPSMonitor.java:166)
[09:25:14] [React Reactor/WARN]: 	at com.volmit.react.util.RQ.run(RQ.java:27)
[09:26:19] [React Reactor/WARN]: java.io.EOFException: Unexpected end of ZLIB input stream
[09:26:19] [React Reactor/WARN]: 	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
[09:26:19] [React Reactor/WARN]: 	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
[09:26:19] [React Reactor/WARN]: 	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
[09:26:19] [React Reactor/WARN]: 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
[09:26:19] [React Reactor/WARN]: 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
[09:26:19] [React Reactor/WARN]: 	at java.io.DataInputStream.readInt(DataInputStream.java:387)
[09:26:19] [React Reactor/WARN]: 	at java.io.DataInputStream.readFloat(DataInputStream.java:446)
[09:26:19] [React Reactor/WARN]: 	at com.volmit.react.api.Datalog.readStream(Datalog.java:67)
[09:26:19] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.merge(DataLogArray.java:106)
[09:26:19] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.condense(DataLogArray.java:81)
[09:26:19] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.continuallyCondense(DataLogArray.java:52)
[09:26:19] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.beginNextStream(DataLogArray.java:346)
[09:26:19] [React Reactor/WARN]: 	at com.volmit.react.api.DataLogArray.sample(DataLogArray.java:438)
[09:26:19] [React Reactor/WARN]: 	at com.volmit.react.controller.DataLogController.onTickAsync(DataLogController.java:96)
[09:26:19] [React Reactor/WARN]: 	at com.volmit.react.util.TPSMonitor$3.run(TPSMonitor.java:166)
[09:26:19] [React Reactor/WARN]: 	at com.volmit.react.util.RQ.run(RQ.java:27)
```

Dunno what this is.

It keeps spamming my console.. forever.

**Comment by EthanTG** [comment]
btw this is still 6.566

**Comment by cyberpwnn** [comment]
Update
