### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by fede1132** [VolmitSoftware/React#427]
Hi, some times i get this error:

```[10:14:59 ERROR]: Could not pass event BlockPhysicsEvent to React v6.545
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.World.a(World.java:567) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.World.applyPhysics(World.java:523) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.World.update(World.java:475) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.World.notifyAndUpdatePhysics(World.java:427) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:411) [server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlock.setTypeIdAndData(CraftBlock.java:145) [server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:167) [server.jar:git-Spigot-596221b-9a1fc1e]
        at org.bukkit.craftbukkit.v1_12_R1.block.CraftBlockState.update(CraftBlockState.java:150) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.BlockFire.b(BlockFire.java:199) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:770) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:308) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:798) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:405) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:678) [server.jar:git-Spigot-596221b-9a1fc1e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:576) [server.jar:git-Spigot-596221b-9a1fc1e]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
        at com.volmit.react.api.LagMap.hit(LagMap.java:109) ~[?:?]
        at com.volmit.react.controller.EventController.on(EventController.java:119) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor50.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-596221b-9a1fc1e]
        ... 19 more
```

**Comment by cyberpwnn** [comment]
Fixed in 6.568
