### ISSUE TITLE
1.13 First and only error I have seen

### ISSUE THREAD

**Issue by CaptainAmpersand** [VolmitSoftware/React#434]
[02:01:12 WARN]: java.io.EOFException
[02:01:12 WARN]:        at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:268)
[02:01:12 WARN]:        at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
[02:01:12 WARN]:        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
[02:01:12 WARN]:        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
[02:01:12 WARN]:        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
[02:01:12 WARN]:        at com.volmit.react.api.Datalog.openReadStream(Datalog.java:40)
[02:01:12 WARN]:        at com.volmit.react.api.DataLogArray.getDuration(DataLogArray.java:126)
[02:01:12 WARN]:        at com.volmit.react.api.DataLogArray.condense(DataLogArray.java:77)
[02:01:12 WARN]:        at com.volmit.react.api.DataLogArray.continuallyCondense(DataLogArray.java:52)
[02:01:12 WARN]:        at com.volmit.react.api.DataLogArray.beginNextStream(DataLogArray.java:346)
[02:01:12 WARN]:        at com.volmit.react.api.DataLogArray.sample(DataLogArray.java:438)
[02:01:12 WARN]:        at com.volmit.react.controller.DataLogController.onTickAsync(DataLogController.java:96)
[02:01:12 WARN]:        at com.volmit.react.util.TPSMonitor.run(TPSMonitor.java:139)

Spigot 1.13-pre7
React 6.565

Gogogogo

**Comment by cyberpwnn** [comment]
This isnt a 1.13 bug. Update to 6.569
