### ISSUE TITLE
./re cap doesn't work in 1.13

### ISSUE THREAD

**Issue by CaptainAmpersand** [VolmitSoftware/React#435]
```[21:16:22 INFO]: Ampersand issued server command: /react capabilities
[21:16:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'react' in plugin React v6.569
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[server.jar:git-Spigot-1d0aef7-b4bff6f]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[server.jar:git-Spigot-1d0aef7-b4bff6f]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:691) ~[server.jar:git-Spigot-1d0aef7-b4bff6f]
        at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1628) ~[server.jar:git-Spigot-1d0aef7-b4bff6f]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1463) ~[server.jar:git-Spigot-1d0aef7-b4bff6f]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[server.jar:git-Spigot-1d0aef7-b4bff6f]
        at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[server.jar:git-Spigot-1d0aef7-b4bff6f]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[server.jar:git-Spigot-1d0aef7-b4bff6f]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_171]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [server.jar:git-Spigot-1d0aef7-b4bff6f]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:845) [server.jar:git-Spigot-1d0aef7-b4bff6f]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [server.jar:git-Spigot-1d0aef7-b4bff6f]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:780) [server.jar:git-Spigot-1d0aef7-b4bff6f]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:678) [server.jar:git-Spigot-1d0aef7-b4bff6f]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Sound.ENDERDRAGON_HIT
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_171]
        at org.bukkit.Sound.valueOf(Sound.java:1) ~[server.jar:git-Spigot-1d0aef7-b4bff6f]
        at com.volmit.react.util.MSound.bukkitSound(MSound.java:229) ~[?:?]
        at com.volmit.react.Gate.msgError(Gate.java:749) ~[?:?]
        at com.volmit.react.command.CommandCapabilities.fire(CommandCapabilities.java:86) ~[?:?]
        at com.volmit.react.controller.CommandController.onCommand(CommandController.java:311) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[server.jar:git-Spigot-1d0aef7-b4bff6f]
        ... 15 more
```
Spigot 1.13-pre7

**Comment by cyberpwnn** [comment]
6.572
