### ISSUE TITLE
Could not pass event BlockPhysicsEvent to React v6.572

### ISSUE THREAD

**Issue by Arin456** [VolmitSoftware/React#445]
![error](https://user-images.githubusercontent.com/33549508/43357570-f9b79ffc-92ad-11e8-883e-3f1a4ac2c559.png)

Full log: https://pastebin.com/pYWQAfTT

Dunno how it happend but it create sum lag when it is shown in da console
Hope dis halp u with da development to 1.13 <3

**Comment by FabioZumbi12** [comment]
The same error!

Here my logs without cuts:

```
[07:06:08] [Server thread/ERROR]: Could not pass event BlockPhysicsEvent to React v6.572
org.bukkit.event.EventException: null
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[patched_1.13.jar:git-Paper-79]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.13.jar:git-Paper-79]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.13.jar:git-Paper-79]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[patched_1.13.jar:git-Paper-79]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[patched_1.13.jar:git-Paper-79]
	at org.bukkit.craftbukkit.v1_13_R1.event.CraftEventFactory.callBlockPhysicsEvent(CraftEventFactory.java:1115) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.BlockPlant.updateState(BlockPlant.java:18) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.BlockTallPlant.updateState(BlockTallPlant.java:17) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.IBlockData.updateState(IBlockData.java:264) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.DefinedStructure.lambda$a$1(DefinedStructure.java:303) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.VoxelShapeDiscrete.a(SourceFile:340) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.VoxelShapeDiscrete.a(SourceFile:317) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.DefinedStructure.a(DefinedStructure.java:292) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.DefinedStructure.a(DefinedStructure.java:162) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.DefinedStructurePiece.a(SourceFile:59) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.WorldGenFeatureOceanRuinPieces$a.a(SourceFile:268) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.StructureStart.a(SourceFile:60) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.StructureGenerator.generate(StructureGenerator.java:50) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.WorldGenDecoratorEmpty.a(SourceFile:16) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.WorldGenDecoratorEmpty.a(SourceFile:13) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.WorldGenFeatureComposite.a(SourceFile:27) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.BiomeBase.a(SourceFile:514) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkGeneratorAbstract.addDecorations(ChunkGeneratorAbstract.java:98) ~[patched_1.13.jar:git-Paper-79]
	at org.bukkit.craftbukkit.v1_13_R1.generator.NormalChunkGenerator.addDecorations(NormalChunkGenerator.java:59) ~[patched_1.13.jar:git-Paper-79]
	at co.aikar.timings.TimedChunkGenerator.addDecorations(TimedChunkGenerator.java:106) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkTaskDecorate.a(SourceFile:12) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkTask.a(SourceFile:35) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:95) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkTaskScheduler.a(ChunkTaskScheduler.java:64) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkTaskScheduler.a(ChunkTaskScheduler.java:17) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:130) ~[patched_1.13.jar:git-Paper-79]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_181]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.jar:git-Paper-79]
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(CompletableFuture.java:529) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:599) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:617) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.thenApplyAsync(CompletableFuture.java:1993) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:130) ~[patched_1.13.jar:git-Paper-79]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:105) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:22) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-79]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:105) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:22) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-79]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:105) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkStatus.a(SourceFile:22) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:126) ~[patched_1.13.jar:git-Paper-79]
	at java.util.Map.computeIfAbsent(Map.java:957) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:120) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.Scheduler$a.a(SourceFile:98) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.Scheduler.a(SourceFile:60) ~[patched_1.13.jar:git-Paper-79]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) ~[?:1.8.0_181]
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:260) ~[patched_1.13.jar:git-Paper-79]
	at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1604) ~[?:1.8.0_181]
	at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:1830) ~[?:1.8.0_181]
	at net.minecraft.server.v1_13_R1.Scheduler.b(SourceFile:61) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.SchedulerBatch.a(SourceFile:39) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkProviderServer.generateChunk(ChunkProviderServer.java:182) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkProviderServer.generateChunk(ChunkProviderServer.java:172) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:134) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.PlayerChunk.a(PlayerChunk.java:96) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.PlayerChunkMap.flush(PlayerChunkMap.java:159) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.WorldServer.doTick(WorldServer.java:322) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:1043) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:914) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:812) ~[patched_1.13.jar:git-Paper-79]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.RuntimeException: Batch already started.
	at net.minecraft.server.v1_13_R1.SchedulerBatch.b(SourceFile:27) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkProviderServer.generateChunk(ChunkProviderServer.java:176) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkProviderServer.generateChunk(ChunkProviderServer.java:172) ~[patched_1.13.jar:git-Paper-79]
	at net.minecraft.server.v1_13_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:134) ~[patched_1.13.jar:git-Paper-79]
	at org.bukkit.craftbukkit.v1_13_R1.CraftWorld.getChunkAt(CraftWorld.java:181) ~[patched_1.13.jar:git-Paper-79]
	at org.bukkit.craftbukkit.v1_13_R1.CraftWorld.getChunkAt(CraftWorld.java:185) ~[patched_1.13.jar:git-Paper-79]
	at org.bukkit.craftbukkit.v1_13_R1.block.CraftBlock.getChunk(CraftBlock.java:94) ~[patched_1.13.jar:git-Paper-79]
	at com.volmit.react.controller.EventController.on(EventController.java:121) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor42.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[patched_1.13.jar:git-Paper-79]
```

**Comment by cyberpwnn** [comment]
Fixed (as much as i can, because its a bug in paper) in 6.573
