### ISSUE TITLE
Constant error spam in console (React 6.587)

### ISSUE THREAD

**Issue by James76931** [VolmitSoftware/React#472]
Hi.

After updating to React 6.587, I'm getting this message constantly spammed in the server console:
`[19:35:26] [Craft Scheduler Thread - 23/WARN]: [React] Plugin React v6.587 generated an exception while executing task 41437
java.lang.NullPointerException: null
at com.volmit.react.controller.RAIController$1.run(RAIController.java:76) ~[?:?]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-513]
at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-513]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-513]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

**Comment by James76931** [comment]
Just an extra note, when the plugin initialises, this error appears too:
`[19:43:12] [Server thread/INFO]: [React] Enabling React v6.587*
[19:43:13] [Server thread/INFO]: [React] Selected R1_13
[19:43:13] [Server thread/WARN]: java.lang.IllegalArgumentException: No enum constant com.volmit.react.api.ActionType.LOCK_FLUID
[19:43:13] [Server thread/WARN]: at java.lang.Enum.valueOf(Enum.java:238)
[19:43:13] [Server thread/WARN]: at com.volmit.react.api.ActionType.valueOf(ActionType.java:1)
[19:43:13] [Server thread/WARN]: at com.volmit.react.xrai.VirtualAction.<init>(VirtualAction.java:30)
[19:43:13] [Server thread/WARN]: at com.volmit.react.xrai.RAIGoal.<init>(RAIGoal.java:109)
[19:43:13] [Server thread/WARN]: at com.volmit.react.xrai.GoalManager.loadGoals(GoalManager.java:258)
[19:43:13] [Server thread/WARN]: at com.volmit.react.api.RAI.<init>(RAI.java:25)
[19:43:13] [Server thread/WARN]: at com.volmit.react.controller.RAIController.start(RAIController.java:30)
[19:43:13] [Server thread/WARN]: at com.volmit.react.ReactPlugin.onEnable(ReactPlugin.java:93)
[19:43:13] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[19:43:13] [Server thread/WARN]: at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:326)
[19:43:13] [Server thread/WARN]: at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[19:43:13] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:443)
[19:43:13] [Server thread/WARN]: at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:357)
[19:43:13] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:236)
[19:43:13] [Server thread/WARN]: at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:786)
[19:43:13] [Server thread/WARN]: at java.lang.Thread.run(Thread.java:748)
[19:43:13] [Server thread/INFO]: React: Language: enUS
[19:43:13] [Server thread/INFO]: 1.13`

**Comment by Zethrus** [comment]
Can confirm, I also get a similar error... I have had to disable React temporarily until this is resolved as it's filling my server logs too quickly by spamming every millisecond...
`
 [00:50:48 WARN]: [React] Plugin React v6.587 generated an exception while executing task 4469001
java.lang.NullPointerException: null
        at com.volmit.react.controller.RAIController$1.run(RAIController.java:76) ~[React-6.587.jar:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot.jar:git-Spigot-f56e2e7-ad6070d]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot.jar:git-Spigot-f56e2e7-ad6070d]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191] 
`
