### ISSUE TITLE
ConcurrentModification with /re map turned on (1.13.2)

### ISSUE THREAD

**Issue by i0xHeX** [VolmitSoftware/React#482]
Stack trace:
```
[21:55:42] [Craft Scheduler Thread - 39/WARN]: [React] Plugin React v6.595 generated an exception while executing task 301307
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_191]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_191]
	at primal.lang.collection.GList.<init>(GList.java:87) ~[?:?]
	at primal.lang.collection.GMap.k(GMap.java:122) ~[?:?]
	at com.volmit.react.api.PlotBoard.earilestRecording(PlotBoard.java:98) ~[?:?]
	at com.volmit.react.api.PlotBoard.clean(PlotBoard.java:23) ~[?:?]
	at com.volmit.react.api.PlotBoard.plot(PlotBoard.java:200) ~[?:?]
	at com.volmit.react.api.GraphSampleLine.sample(GraphSampleLine.java:43) ~[?:?]
	at com.volmit.react.controller.GraphController$2.run(GraphController.java:148) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-521]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-521]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-521]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by cyberpwnn** [comment]
Fixed
