### ISSUE TITLE
Cant load v6.606 for papermc 1.13

### ISSUE THREAD

**Issue by CGsama** [VolmitSoftware/React#489]
[10:23:07 INFO]: Loaded 0 recipes
[10:23:08 INFO]: Starting minecraft server version 1.13
[10:23:08 INFO]: Loading properties
[10:23:08 INFO]: Default game type: SURVIVAL
[10:23:08 INFO]: This server is running Paper version git-Paper-172 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
[10:23:09 INFO]: Debug logging is disabled
[10:23:09 INFO]: Server Ping Player Sample Count: 12
[10:23:09 INFO]: Using 4 threads for Netty based IO
[10:23:09 INFO]: Generating keypair
[10:23:09 INFO]: Starting Minecraft server on *:25565
[10:23:09 INFO]: Using default channel type
[10:23:14 INFO]: Set PluginClassLoader as parallel capable
[10:23:14 INFO]: [React] Loading React v6.606
[10:23:14 INFO]: Server permissions file permissions.yml is empty, ignoring it
[10:23:14 INFO]: [React] Enabling React v6.606*
[10:23:14 ERROR]: Error occurred while enabling React v6.606 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.volmit.react.ReactPlugin.initNMS(ReactPlugin.java:220) ~[?:?]
        at com.volmit.react.ReactPlugin.start(ReactPlugin.java:57) ~[?:?]
        at primal.bukkit.plugin.PrimalPlugin.onEnable(PrimalPlugin.java:63) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[papermc-1.13.jar:git-Paper-172]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:325) ~[papermc-1.13.jar:git-Paper-172]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[papermc-1.13.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:433) ~[papermc-1.13.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[papermc-1.13.jar:git-Paper-172]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:231) ~[papermc-1.13.jar:git-Paper-172]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764) ~[papermc-1.13.jar:git-Paper-172]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
        at primal.bukkit.nms.Catalyst.getHost(Catalyst.java:11) ~[?:?]
        at primal.bukkit.nms.Catalyst.<clinit>(Catalyst.java:5) ~[?:?]
        ... 11 more
[10:23:14 INFO]: [React] Disabling React v6.606
[10:23:14 ERROR]: Error occurred while disabling React v6.606 (Is it up to date?)
java.lang.NullPointerException: null
        at com.volmit.react.ReactPlugin.stop(ReactPlugin.java:195) ~[?:?]
        at primal.bukkit.plugin.PrimalPlugin.onDisable(PrimalPlugin.java:69) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[papermc-1.13.jar:git-Paper-172]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:359) ~[papermc-1.13.jar:git-Paper-172]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) ~[papermc-1.13.jar:git-Paper-172]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[papermc-1.13.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugin(CraftServer.java:433) ~[papermc-1.13.jar:git-Paper-172]
        at org.bukkit.craftbukkit.v1_13_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[papermc-1.13.jar:git-Paper-172]
        at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:231) ~[papermc-1.13.jar:git-Paper-172]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:764) ~[papermc-1.13.jar:git-Paper-172]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]

**Comment by DavidRockin** [comment]
Hi, if you are still experiencing this issue, you will need to a newer version of 1.13.x
