### ISSUE TITLE
Console Error

### ISSUE THREAD

**Issue by UnoriginalName** [VolmitSoftware/React#491]
`[13:41:05 WARN]: [React] Plugin React v6.609 generated an exception while executing task 1116252
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_191]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_191]
        at primal.lang.collection.GList.<init>(GList.java:87) ~[?:?]
        at primal.lang.collection.GMap.k(GMap.java:122) ~[?:?]
        at com.volmit.react.controller.EntityCullController$1.run(EntityCullController.java:144) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[patched_1.13.2.jar:git-Paper-564]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-564]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-564]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
`
Happens randomly on the server, issue with java version or is it something else? Running JDK 8

**Comment by jascotty2** [comment]
This issue is still occurring in React 6.61

```
[19:02:05 WARN]: [React] Plugin React v6.61 generated an exception while executing task 4272118
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437) ~[?:1.8.0_131]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1461) ~[?:1.8.0_131]
        at primal.lang.collection.GList.<init>(GList.java:87) ~[?:?]
        at primal.lang.collection.GMap.k(GMap.java:122) ~[?:?]
        at com.volmit.react.controller.EntityCullController$1.run(EntityCullController.java:144) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.13.2.jar:git-Paper-614]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.13.2.jar:git-Paper-614]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.13.2.jar:git-Paper-614]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
```

**Comment by jascotty2** [comment]
Additional information about the error: 
- Running paper-614 (MC 1.13.2)
- Error occurs about every 20 seconds
- Have not made any changes to the config
