### ISSUE TITLE
1.14.3 Error Advancements

### ISSUE THREAD

**Issue by CaptainAmpersand** [VolmitSoftware/React#502]
Server: 1.14.3 Paper 127
React Version 6.612
```[00:11:01] [Server thread/WARN]: [React] Task #112622 for React v6.612 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_13_R2/inventory/CraftItemStack
	at primal.bukkit.nms.AdvancementHolder14.getMinecraftIDFrom(AdvancementHolder14.java:409) ~[?:?]
	at primal.bukkit.nms.AdvancementHolder14.withIcon(AdvancementHolder14.java:111) ~[?:?]
	at primal.bukkit.nms.Catalyst14.sendAdvancement(Catalyst14.java:47) ~[?:?]
	at primal.bukkit.nms.NMP$MESSAGE$1.run(NMP.java:97) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.3.jar:git-Paper-127]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1132) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[patched_1.14.3.jar:git-Paper-127]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.14.3.jar:git-Paper-127]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]```

Created after turning on advancement changes in the config, and those changes being hotloaded onto the server.

**Comment by DavidRockin** [comment]
Looks like I somehow messed up the imports for 1.14.x for Primal.

Can you specify the steps to reproduce this issue?

**Comment by CaptainAmpersand** [comment]
Honestly all I did was turn it on in the config, and save. It hotloaded config changes, and gave me that error as a result.

**Comment by DavidRockin** [comment]
Cool, It's been fixed. Thanks
