### ISSUE TITLE
Report error in Paper 1.14.3

### ISSUE THREAD

**Issue by In77** [VolmitSoftware/React#508]
Java version = JDK8u212
Server version = Paper 1.14.3 build 134
Plugin version = 6.612

React 6.612 will report error while server loaded a chunk with lot of hoppers
(player's redstone machine called Super-furnace):

[07:28:33 ERROR]: Could not pass event InventoryMoveItemEvent to React v6.612
java.lang.NullPointerException: null
        at com.volmit.react.controller.EventController.on(EventController.java:165) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor62.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.callPushMoveEvent(TileEntityHopper.java:280) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.hopperPush(TileEntityHopper.java:213) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.t(TileEntityHopper.java:351) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.a(TileEntityHopper.java:135) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.TileEntityHopper.tick(TileEntityHopper.java:117) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.World.tickBlockEntities(World.java:855) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.WorldServer.doTick(WorldServer.java:378) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1192) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:420) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1064) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:908) ~[PaperClip-1.14.3-b134.jar:git-Paper-134]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by DavidRockin** [comment]
@In77 @NmChris are you able to reproduce it manually? Do you know of any blocks hoppers are interacting with to produce this error?

**Comment by NmChris** [comment]
@DavidRockin No clue what's causing it / who's causing it I'll try to find out

**Comment by DavidRockin** [comment]
Any updates with this issue?

**Comment by In77** [comment]
The Error will show when ticking this machine:
<img width="727" alt="Screenshot 2019-08-01 at 10 16 09" src="https://user-images.githubusercontent.com/44344308/62260732-965e0d00-b445-11e9-8e20-9c009a57402d.png">
<img width="1161" alt="Screenshot 2019-08-01 at 10 14 02" src="https://user-images.githubusercontent.com/44344308/62260734-9958fd80-b445-11e9-9e05-920f50153726.png">

**Comment by DavidRockin** [comment]
Thanks, I can confirm this is reproducible with composters.

**Comment by DavidRockin** [comment]
Resolved in 53d0178
