### ISSUE TITLE
React Error in Console

### ISSUE THREAD

**Issue by Riknesh** [VolmitSoftware/React#516]
I seem to be getting this error on console randomly.

`[22:04:25] [Server thread/WARN]: [React] Task #369575 for React v6.614 generated an exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_222]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_222]
	at primal.lang.collection.GList.<init>(GList.java:122) ~[?:?]
	at primal.lang.collection.GMap.v(GMap.java:142) ~[?:?]
	at com.volmit.react.api.LagMap.getGrandTotal(LagMap.java:36) ~[?:?]
	at com.volmit.react.api.LagMapChunk.getPercent(LagMapChunk.java:51) ~[?:?]
	at com.volmit.react.command.CommandTopChunk.update(CommandTopChunk.java:111) ~[?:?]
	at com.volmit.react.command.CommandTopChunk.access$000(CommandTopChunk.java:37) ~[?:?]
	at com.volmit.react.command.CommandTopChunk$1.run(CommandTopChunk.java:77) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-176]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-176]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1148) ~[patched_1.14.4.jar:git-Paper-176]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-176]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1075) ~[patched_1.14.4.jar:git-Paper-176]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:919) ~[patched_1.14.4.jar:git-Paper-176]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

Running React version 6.614
Server version: PaperSpigot 1.14.4

**Comment by DavidRockin** [comment]
Please follow the issue template. Can you provide any information on how to reproduce this?

**Comment by Riknesh** [comment]
The error appears randomly on the console...I dont exactly know how to replicate it
