### ISSUE TITLE
java.net.UnknownHostException

### ISSUE THREAD

**Issue by PassiAPI** [VolmitSoftware/React#517]
Cull Entity Action:

[16:13:12 WARN]: java.net.UnknownHostException: paste.volmit.com
[16:13:12 WARN]:        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
[16:13:12 WARN]:        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[16:13:12 WARN]:        at java.net.Socket.connect(Socket.java:589)
[16:13:12 WARN]:        at java.net.Socket.connect(Socket.java:538)
[16:13:12 WARN]:        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
[16:13:12 WARN]:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
[16:13:12 WARN]:        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
[16:13:12 WARN]:        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
[16:13:12 WARN]:        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
[16:13:12 WARN]:        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
[16:13:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
[16:13:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
[16:13:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
[16:13:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
[16:13:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1340)
[16:13:12 WARN]:        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1315)
[16:13:12 WARN]:        at com.volmit.react.util.Paste.paste(Paste.java:43)
[16:13:12 WARN]:        at com.volmit.react.action.ActionDump$1.run(ActionDump.java:63)
[16:13:12 WARN]:        at com.volmit.react.util.RQ.run(RQ.java:27)

Version: Paper 1.14.4

**Comment by relavis** [comment]
Fixed with above commit
