### ISSUE TITLE
Remote Client not working

### ISSUE THREAD

**Issue by ASweetOldMan** [VolmitSoftware/React#521]
The config does not match the setup guide in the documentation, but I think it was just moved to the legacy section.  

Config:

```
legacy:
       remote-server:

        # Use the legacy remote server (for react remote)
        enable-react-remote-server: true

        # The port to bind to when the remote server is enabled. This cannot be your
        # server port or an already used port.
        remote-port: 8128
```

the user is set up in remote-users per the setup and I am connecting via the LAN IP of the server on port 8128.  The first time I set it up and clicked connect, it connected fine.  I clicked on the console tab and I got the "error connecting" popup shortly after.  I cannot reconnect now.

console with stack trace
```
[23:30:50] [React Reactor/INFO]: [React Server]: Loading Remote Users
[23:30:50] [React Reactor/INFO]: [React Server]: Loaded User: asweetoldman
[23:31:14] [React Legacy Remote Server/WARN]: Exception in thread "React Legacy Remote Server" 
[23:31:14] [React Legacy Remote Server/WARN]: com.volmit.react.util.JSONException: JSON does not allow non-finite numbers.
[23:31:14] [React Legacy Remote Server/WARN]: 	at com.volmit.react.util.JSONObject.testValidity(JSONObject.java:1726)
[23:31:14] [React Legacy Remote Server/WARN]: 	at com.volmit.react.util.JSONObject.put(JSONObject.java:1431)
[23:31:14] [React Legacy Remote Server/WARN]: 	at com.volmit.react.legacy.server.PacketResponse.put(PacketResponse.java:24)
[23:31:14] [React Legacy Remote Server/WARN]: 	at com.volmit.react.legacy.server.ReactServer.handleCommand(ReactServer.java:174)
[23:31:14] [React Legacy Remote Server/WARN]: 	at com.volmit.react.legacy.server.ReactServer.run(ReactServer.java:122)
```

World's lowest quality video of it: https://www.youtube.com/watch?v=RjEtUat4cvo

**Comment by relavis** [comment]
This is such an old bug, but it'll be fixed with 6.648
