### ISSUE TITLE
1.15 NMS issue

### ISSUE THREAD

**Issue by kbartek05** [VolmitSoftware/React#525]
**Describe the bug**
Trying to enable/disable the plugin doesn't work and throws an exception while executing initNMS().

**To Reproduce**
1. Install React on a 1.15(.1) server
2. Start the server

**Expected behavior**
React should start (NMS safe mode is enabled)

**Screenshots or Video Recordings**
Exception:
```java
[15:05:53 INFO]: [React] Enabling React v6.612*
[15:05:53 ERROR]: Error occurred while enabling React v6.612 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.volmit.react.ReactPlugin.initNMS(ReactPlugin.java:232) ~[?:?]
        at com.volmit.react.ReactPlugin.start(ReactPlugin.java:69) ~[?:?]
        at primal.bukkit.plugin.PrimalPlugin.onEnable(PrimalPlugin.java:63) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-25]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:227) ~[patched_1.15.1.jar:git-Paper-25]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-25]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NullPointerException
        at primal.bukkit.nms.Catalyst.getHost(Catalyst.java:11) ~[?:?]
        at primal.bukkit.nms.Catalyst.<clinit>(Catalyst.java:5) ~[?:?]
        ... 11 more
[15:05:53 INFO]: [React] Disabling React v6.612
[15:05:53 ERROR]: Error occurred while disabling React v6.612 (Is it up to date?)
java.lang.NullPointerException: null
        at com.volmit.react.ReactPlugin.stop(ReactPlugin.java:207) ~[?:?]
        at primal.bukkit.plugin.PrimalPlugin.onDisable(PrimalPlugin.java:69) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:373) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:453) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:468) ~[patched_1.15.1.jar:git-Paper-25]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:382) ~[patched_1.15.1.jar:git-Paper-25]
        at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:227) ~[patched_1.15.1.jar:git-Paper-25]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884) ~[patched_1.15.1.jar:git-Paper-25]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

```

**Server and Plugin Informations**
 - Installed plugins: <personal plugin>, AuthMe, Cenotaph, CraftingStore, CS-CoreLib, DangerousCaves, DiscordSRV, dynmap, EasyPrefix, Essentials, ExtraGear, FastLogin, Harbor, Hibernate*, HotbarPets, LuckPerms, Matrix, PhysicsToGo, PlaceholderAPI, PlugMan, ProtectionStones, ProtocolLib, React*, Scoreboard-revision*, SkinsRestorer, Skript, skUtilities*, Slimefun, SuperLuckyBlock, Vault, WhatIsThis, WorldBorder, WorldEdit, WorldGuard, XPFromHarvest
 - React Version: React v6.612
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: PaperSpigot 1.15.1
 - Operating System (if applicable): Java 1.8 (OpenJDK 64-Bit Server VM 25.232-b09) Host:  Linux 4.9.0-11-amd64 (amd64)

**Additional context**
Add any other context about the problem here, server timings reports, React dump information, complete console log etc. Please do not make Pastebin dumps or screenshot expire.

**Comment by cyberpwnn** [comment]
Thanks,

**Comment by cyberpwnn** [comment]
Update :P
