### ISSUE TITLE
[Warning] java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by Baktus79** [VolmitSoftware/React#530]
**Describe the bug**
Getting this warning message in the console often.

**Screenshots or Video Recordings**
```
[18:12:09 WARN]: [React] Plugin React v6.617 generated an exception while executing task 23777359
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_201]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1469) ~[?:1.8.0_201]
        at primal.lang.collection.GList.<init>(GList.java:87) ~[?:?]
        at primal.lang.collection.GMap.k(GMap.java:122) ~[?:?]
        at com.volmit.react.controller.EntityCullController$1.run(EntityCullController.java:145) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-55]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.1.jar:git-Paper-55]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.1.jar:git-Paper-55]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
```

**Server and Plugin Informations**
 - React Version: 6,617
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: Paperspigot 1.15.1
 - Operating System (if applicable): Ubuntu 18.04

**Comment by MrAureliusR** [comment]
Can confirm, same issue, both with 6.614 and 6.617, on Paper (both 1.14.4 and 1.15.2).

**Comment by toriato** [comment]
Looks like flying machine causing the issue.

**Comment by dweSheppard** [comment]
Can confirm on spigot-1.15.2 with version 6.618
