### ISSUE TITLE
The server keeps refreshing 1.12.2

### ISSUE THREAD

**Issue by Edwiinsgm** [VolmitSoftware/React#533]
The server keeps refreshing

[14:48:18] [Server thread/WARN]: Thaumcraft loaded a new chunk [46, 450] in dimension 0 (overworld) while populating chunk [47, 450], causing cascading worldgen lag.
[14:48:18] [Server thread/WARN]: Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
[14:48:19] [Server thread/ERROR]: Could not pass event InventoryMoveItemEvent to React v6.617
java.lang.AbstractMethodError: null
        at org.bukkit.craftbukkit.v1_12_R1.inventory.CraftInventory.getLocation(CraftInventory.java:528) ~[CraftInventory.class:git-CatServer-1.12.2-b19657a]
        at com.volmit.react.controller.EventController.on(EventController.java:167) ~[?:?]
        at catserver.server.executor.asm.generated.GeneratedEventExecutor55.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:67) ~[EventExecutor$2.class:git-CatServer-1.12.2-b19657a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-CatServer-1.12.2-b19657a]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:509) [SimplePluginManager.class:git-CatServer-1.12.2-b19657a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:494) [SimplePluginManager.class:git-CatServer-1.12.2-b19657a]
        at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:169) [VanillaInventoryCodeHooks.class:git-CatServer-1.12.2-b19657a]
        at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:246) [avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:189) [avw.class:?]
        at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:170) [avw.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:2165) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:747) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:935) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:469) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:804) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]

**Comment by Frerduro** [comment]
This is a forge server react does not support forge

**Comment by relavis** [comment]
React does not support Forge.
