### ISSUE TITLE
RuntimeException on server close

### ISSUE THREAD

**Issue by D3nied** [VolmitSoftware/React#539]
**Describe the bug**
A Java RuntimeException

**To Reproduce**
stop the server with stop command

**Expected behavior**
i guess no RuntimeException is the expected behavoir
`[02:14:32 INFO]: [React] Disabling React v6.618
[02:14:32 ERROR]: Error occurred while disabling React v6.618 (Is it up to date?)
java.lang.RuntimeException: Listener is already closed
        at primal.bukkit.nms.CatalystPacketListener.closeListener(CatalystPacketListener.java:118) ~[?:?]
        at primal.bukkit.nms.Catalyst15.stop(Catalyst15.java:173) ~[?:?]
        at com.volmit.react.ReactPlugin.stopNMS(ReactPlugin.java:233) ~[?:?]
        at com.volmit.react.ReactPlugin.stop(ReactPlugin.java:202) ~[?:?]
        at primal.bukkit.plugin.PrimalPlugin.onDisable(PrimalPlugin.java:69) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:372) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495) ~[patched_1.15.2.jar:git-Paper-183]
        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.disablePlugins(CraftServer.java:404) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.stop(MinecraftServer.java:747) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.DedicatedServer.stop(DedicatedServer.java:752) ~[patched_1.15.2.jar:git-Paper-183]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:981) ~[patched_1.15.2.jar:git-Paper-183]
        at java.lang.Thread.run(Unknown Source) [?:?]`

**Server and Plugin Informations**
 - ProtocolLib,React
 - React Version: v6,618
 - Server Platform and Version : Paperspigot version git-Paper-183 (MC: 1.15.2)
 - Operating System (if applicable): Windows

**Comment by relavis** [comment]
I've tracked this down to being an issue with the TinyProtocol class used in Primal. 
https://github.com/dmulloy2/ProtocolLib/issues/788

**Comment by relavis** [comment]
I've added a printStackTrace on line 107 of primal.bukkit.nms.CatalystPacketListener.class. Starting the server now throws this error:
https://hastebin.com/wofenogoqu

This allows us to track it down to Primal, and more specifically, TinyProtocol.
