### ISSUE TITLE
/re map causes NPE when viewing Server Tick MS graph

### ISSUE THREAD

**Issue by relavis** [VolmitSoftware/React#546]
**Describe the bug**
An NPE occurs every few seconds in console while viewing the Server Tick MS graph under the Tick tab.

**To Reproduce**
1. Do /re map
2. Scroll to the Tick tab and make sure the Server Tick MS graph is visible
3. Look in console

**Expected behavior**
No errors in console

**Screenshots or Video Recordings**
`[19:03:11 WARN]: [React] Plugin React v6.618 generated an exception while executing task 2282151
java.lang.NullPointerException: null
        at com.volmit.react.api.GraphSampleLine.scaleFor(GraphSampleLine.java:272) ~[?:?]
        at com.volmit.react.api.GraphSampleLine.onRender(GraphSampleLine.java:65) ~[?:?]
        at com.volmit.react.api.NormalGraph.render(NormalGraph.java:39) ~[?:?]
        at com.volmit.react.api.ColossalView.render(ColossalView.java:78) ~[?:?]
        at com.volmit.react.api.GraphingInstance$1.draw(GraphingInstance.java:64) ~[?:?]
        at com.volmit.react.api.Papyrus$1.run(Papyrus.java:99) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-347]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-347]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-347]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]`

**Server and Plugin Informations**
 - Installed plugins: React
 - React Version: 6.618
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: PaperSpigot 1.15.2 Build 347
 - Operating System (if applicable): CentOS 8

**Additional context**
N/A - Adding this issue here so I can assess it further and see if anyone else has a similar bug

**Comment by relavis** [comment]
After some testing, I've found that the NPE only occurs in between two specific buffered frames. 

`[K[20:47:10 INFO]: com.volmit.react.api.BufferedFrame@3e671813
> 
[K[33;1m[20:47:10 WARN]: [React] Plugin React v6.618 generated an exception while executing task 122538
java.lang.NullPointerException: null
	at com.volmit.react.api.GraphSampleLine.scaleFor(GraphSampleLine.java:272) ~[?:?]
	at com.volmit.react.api.GraphSampleLine.onRender(GraphSampleLine.java:65) ~[?:?]
	at com.volmit.react.api.NormalGraph.render(NormalGraph.java:39) ~[?:?]
	at com.volmit.react.api.ColossalView.render(ColossalView.java:79) ~[?:?]
	at com.volmit.react.api.GraphingInstance$1.draw(GraphingInstance.java:64) ~[?:?]
	at com.volmit.react.api.Papyrus$1.run(Papyrus.java:99) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Paper-347]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-347]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-347]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
[m> 
[K[20:47:10 INFO]: com.volmit.react.api.BufferedFrame@6584896d`

I've found 7 instances of this NPE happening between these two frames.
