### ISSUE TITLE
React wont work with 1.16.2 beta. (PaperMC)

### ISSUE THREAD

**Issue by xManInWhitex** [VolmitSoftware/React#562]
**Describe the bug**
 - PaperMC 1.16.2-R3 cant load React 6.634

**To Reproduce**
 - Install React on PaperMC 1.16.2-R3

**Server and Plugin Informations**
 - React 6.634
 - PaperMC 1.16.2-R3

**Additional context**
'[22:16:55 INFO]: [React] Enabling React v6.634*
[22:16:55 INFO]: ,---.               |
[22:16:55 INFO]: |---',---.,---.,---.|---
[22:16:55 INFO]: |  \ |---',---||    |
[22:16:55 INFO]: `   ``---'`---^`---'`---'
[22:16:55 ERROR]: Error occurred while enabling React v6.634 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at com.volmit.react.ReactPlugin.initNMS(ReactPlugin.java:241) ~[?:?]
        at com.volmit.react.ReactPlugin.start(ReactPlugin.java:66) ~[?:?]
        at primal.bukkit.plugin.PrimalPlugin.onEnable(PrimalPlugin.java:63) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
        at primal.bukkit.nms.Catalyst.getHost(Catalyst.java:11) ~[?:?]
        at primal.bukkit.nms.Catalyst.<clinit>(Catalyst.java:5) ~[?:?]
        ... 12 more
[22:16:55 INFO]: [React] Disabling React v6.634
[22:16:55 ERROR]: Error occurred while disabling React v6.634 (Is it up to date?)
java.lang.NullPointerException: null
        at com.volmit.react.ReactPlugin.stop(ReactPlugin.java:199) ~[?:?]
        at primal.bukkit.plugin.PrimalPlugin.onDisable(PrimalPlugin.java:69) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:384) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugin(CraftServer.java:499) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at org.bukkit.craftbukkit.v1_16_R2.CraftServer.enablePlugins(CraftServer.java:413) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at net.minecraft.server.v1_16_R2.DedicatedServer.init(DedicatedServer.java:209) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:939) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.2.jar:git-Paper-"1daafe455"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]'

**Comment by relavis** [comment]
Occurs on Spigot as well. 1.16.2 support in progress.

**Comment by relavis** [comment]
1.16.2 support added with 6.636
