### ISSUE TITLE
[Bug]: React v6.639 generated an exception when using TopChunk command.

### ISSUE THREAD

**Issue by 0xBit-MC** [VolmitSoftware/React#570]
**Describe the bug**
When I use the command, "/react top" or "/react topchunk", to determine which chunks are impacting server performance, the console is spammed with a generated exception.

**To Reproduce**
1. Enter the game server
2. Use the command, "/react top" or "/react topchunk"
3. View the console
4. See the generated exception.

**Expected behavior**
A list of chunks, from highest impactful to lowest impactful will be displayed in a ChestGUI.

**Server and Plugin Informations**
 - Installed plugins: AuctionHouse, BetterSleeping3, BroadcastXS*, BuycraftX, ChatControl, ChestShop, ChestShop-towny*, CombatLogX, CommandBlocker, CoreProtect, dynmap*, Dynmap-Towny, Essentials, EssentialsChat, EssentialsGeoIP, Graves, Jobs, LuckPerms, ProtocolLib, React*, SilkSpawners, Skript, Towny, TownyChat, TownyNameUpdater, Vault, Votifier, VotingPlugin, WorldBorder, WorldEdit, WorldGuard
 - React Version: 6.639
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: Paper 1.16.3
 - Operating System (if applicable): Linux Ubuntu Server

**Additional context**
Log: 
`[17:09:48 WARN]: [React] Task #5028735 for React v6.639 generated an exception
java.lang.NegativeArraySizeException: -1
        at java.util.AbstractCollection.toArray(AbstractCollection.java:139) ~[?:?]
        at java.util.ArrayList.addAll(ArrayList.java:702) ~[?:?]
        at primal.lang.collection.GList.<init>(GList.java:112) ~[?:?]
        at primal.lang.collection.GMap.v(GMap.java:142) ~[?:?]
        at com.volmit.react.api.LagMapChunk.totalScore(LagMapChunk.java:146) ~[?:?]
        at com.volmit.react.api.LagMap.sorted(LagMap.java:144) ~[?:?]
        at com.volmit.react.command.CommandTopChunk.update(CommandTopChunk.java:95) ~[?:?]
        at com.volmit.react.command.CommandTopChunk.access$000(CommandTopChunk.java:38) ~[?:?]
        at com.volmit.react.command.CommandTopChunk$1.run(CommandTopChunk.java:78) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-240]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1296) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:371) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1211) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Paper-240]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-240]
`

**Comment by 0xBit-MC** [comment]
See also: https://github.com/VolmitSoftware/React/issues/569

**Comment by 0xBit-MC** [comment]
@Frerduro it appears @relavis unassigned themselves, could we find a new person to assign this too? The error still persists.
