### ISSUE TITLE
[BUG] exception while executing task

### ISSUE THREAD

**Issue by 0xBit-MC** [VolmitSoftware/React#571]
**Describe the bug**
The bug appears in the console every 15-20 seconds, causing a short interruption in player movement, abilities and etc.

**To Reproduce**
1. Go to console
2. See error

**Expected behavior**
I expect the plugin to run smoothy and not run into exceptions while executing tasks

**Screenshots or Video Recordings**
If applicable, add screenshots or video recordings to help explain your problem.

**Server and Plugin Informations**
 - Installed plugins:
 - React Version: 6.639
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: Paper 1.16.3 (recent build)
 - Operating System (if applicable): Linux Ubuntu Server 20.+

**Additional context**
LOG: 
`[16:29:49 WARN]: [React] Plugin React v6.639 generated an exception while executing task 42387049
java.lang.NegativeArraySizeException: -12
        at java.util.AbstractCollection.toArray(AbstractCollection.java:139) ~[?:?]
        at java.util.ArrayList.addAll(ArrayList.java:702) ~[?:?]
        at primal.lang.collection.GList.<init>(GList.java:80) ~[?:?]
        at primal.lang.collection.GMap.k(GMap.java:122) ~[?:?]
        at com.volmit.react.xrai.Finder.high(Finder.java:73) ~[?:?]
        at com.volmit.react.xrai.VirtualAction.execute(VirtualAction.java:56) ~[?:?]
        at com.volmit.react.xrai.GoalManager.tick(GoalManager.java:74) ~[?:?]
        at com.volmit.react.api.RAI.tick(RAI.java:43) ~[?:?]
        at com.volmit.react.controller.RAIController$1.run(RAIController.java:81) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Paper-246]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.3.jar:git-Paper-246]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.3.jar:git-Paper-246]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
`

**Comment by 0xBit-MC** [comment]
@Frerduro it appears @relavis unassigned themselves, could we find a new person to assign this too? The error still persists.

**Comment by relavis** [comment]
Can you test to see if this error still persists on the newest version?
