### ISSUE TITLE
PlayerLoginEvent Exception

### ISSUE THREAD

**Issue by NotZer0Two** [VolmitSoftware/React#619]
**Describe the bug**
when users join the server make this exception

**To Reproduce**
1.Just join

**Expected behavior**
The error don't happen

**Screenshots or Video Recordings**
If applicable, add screenshots or video recordings to help explain your problem.

**Server and Plugin Informations**
 - Installed plugins:  2FA, AdvancedEnchantments, AdvancedReplay, ajParkour, AmethtystMCUtils, AntiCheatReplay, AntiCommandTab, AntiDrop, AuctionMaster, AuthMe, AutoBroadcast, AutoSell, BattlePass, BeastWithdraw, BlockParticles, BountyHunters, BowVoteParty, ChatGames, Citizens, CombatLogX, CommandAlias, CommandNPC, CommandRegions, CommandToItem, Confiscate, ConsoleSpamFix, CrazyCrates, CryptoCurrency, DeluxeMenus, DeluxeTags, Duels, EazyNick, EconomyShopGUI, EpicChatPrefix, Essentials, EssentialsSpawn, EZColors, FastAsyncWorldEdit, FastLogin, GambleBarLite, GuiBalance, Guilds, HolographicDisplays, InfiniteVouchers, InteractiveBooks, InteractiveChat, JukeBox, KnockbackMaster, LuckPerms, Minepacks, MineResetLite, MoneyPouch, MovingDevApi, Multiverse-Core, MVdWPlaceholderAPI, NBTAPI, NoteBlockAPI, OldCombatMechanics, PlaceholderAPI, PlotSquared, PluginManager, PlugMan, PowerLib, PrisonRanksX, ProtocolLib, React, RevEnchants, SimpleRename, SirBlobmanCore, SkinsRestorer, spark, TAB, TitleManager, TradeSystem, UltimateKits, UltimateRepairing, Vault, ViaBackwards, ViaRewind, ViaVersion, VoteRoulette, Votifier, Vulcan, WorldEdit, WorldGuard, WorldGuardFlyStop
 - React Version: v6.646
 - Server Platform and Version [eg: PaperSpigot 1.14.4]: PaperSpigot 1.12.2
 - Operating System (if applicable): Ubuntu

**Additional context**
```
[14:17:04 ERROR]: Could not pass event PlayerLoginEvent to React v6.646
org.bukkit.event.EventException: null
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:37) ~[patched_1.12.2.jar:git-Paper-1620]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.12.2.jar:git-Paper-1620]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:513) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.PlayerList.attemptLogin(PlayerList.java:565) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:152) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:273) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:948) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[patched_1.12.2.jar:git-Paper-1620]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[patched_1.12.2.jar:git-Paper-1620]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.util.NoSuchElementException: packet_handler
        at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:1119) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:260) ~[patched_1.12.2.jar:git-Paper-1620]
        at io.netty.channel.DefaultChannelPipeline.addBefore(DefaultChannelPipeline.java:249) ~[patched_1.12.2.jar:git-Paper-1620]
        at com.comphenix.protocol.injector.netty.PipelineProxy.addBefore(PipelineProxy.java:61) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector$3$1.addBefore(ChannelInjector.java:316) ~[?:?]
        at primal.bukkit.nms.TinyProtocol.injectChannelInternal(TinyProtocol.java:372) ~[?:?]
        at primal.bukkit.nms.TinyProtocol.injectPlayer(TinyProtocol.java:346) ~[?:?]
        at primal.bukkit.nms.TinyProtocol$5.onPlayerLogin(TinyProtocol.java:178) ~[?:?]
        at com.destroystokyo.paper.event.executor.MethodHandleEventExecutor.execute(MethodHandleEventExecutor.java:35) ~[patched_1.12.2.jar:git-Paper-1620]
        ... 13 more
 
```

**Comment by CocoTheOwner** [comment]
React is discontinued. Sorry.
