### ISSUE TITLE
[R6] IllegalStateException: Asynchronous Async Chunk Load

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#87]
The following error was displayed three times right after the startup:
```
[14:57:54 WARN]: java.lang.IllegalStateException: Asynchronous Async Chunk Load! Blocking thread until it returns
[14:57:54 WARN]:        at net.minecraft.server.v1_10_R1.MCUtil.ensureMain(MCUtil.java:40)
[14:57:54 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18)
[14:57:54 WARN]:        at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:163)
[14:57:54 WARN]:        at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:146)
[14:57:54 WARN]:        at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:142)
[14:57:54 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getChunkAt(CraftWorld.java:149)
[14:57:54 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftWorld.getBlockAt(CraftWorld.java:93)
[14:57:54 WARN]:        at org.bukkit.craftbukkit.v1_10_R1.CraftChunk.getTileEntities(CraftChunk.java:110)
[14:57:54 WARN]:        at react.surge.server.WorldMonitor.sampleTileCount(WorldMonitor.java:216)
[14:57:54 WARN]:        at react.surge.server.WorldMonitor.sample(WorldMonitor.java:156)
[14:57:54 WARN]:        at react.surge.server.WorldMonitor.run(WorldMonitor.java:52)
```

TacoSpigot 1.10.2-R0.1-SNAPSHOT
React-6.14168a
EDIT: Couldn't reproduce with Spigot 1.10.2-R0.1-SNAPSHOT

**Comment by cyberpwnn** [comment]
Its a taco issue, but i think i have fixed it from my end anyways on 6.14742a
