### ISSUE TITLE
[R6] NoSuchMethodError: org.bukkit.attribute.AttributeInstance.getDefaultValue()D

### ISSUE THREAD

**Issue by Rbot48** [VolmitSoftware/React#88]
The following error is spamming the server console:
```
[15:39:51 WARN]: [React] Task #65619 for React v6.14168a generated an exception
java.lang.NoSuchMethodError: org.bukkit.attribute.AttributeInstance.getDefaultValue()D
        at react.controller.EntityStackController.stack(EntityStackController.java:83) ~[React-6.14168a-origin.jar:?]
        at react.controller.EntityStackController.checkNear(EntityStackController.java:234) ~[React-6.14168a-origin.jar:?]
        at react.controller.EntityStackController$1.run(EntityStackController.java:259) ~[React-6.14168a-origin.jar:?]
        at react.surge.sched.Task$3.run(Task.java:80) ~[React-6.14168a-origin.jar:?]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[Spigot%201.10.jar:git-Spigot-de459a2-51263e9]
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353) [Spigot%201.10.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:723) [Spigot%201.10.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [Spigot%201.10.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [Spigot%201.10.jar:git-Spigot-de459a2-51263e9]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [Spigot%201.10.jar:git-Spigot-de459a2-51263e9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]
```

Spigot 1.10.2-R0.1-SNAPSHOT
React-6.14168a

**Comment by cyberpwnn** [comment]
Fixed in 6.14742a
